# Generated by Django 4.2.30 on 2026-05-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('LOOKING_AWAY', 'Looking Away'), ('PHONE_DETECTED', 'Phone Detected'), ('TAB_SWITCH', 'Tab Switch'), ('FULLSCREEN_EXIT', 'Fullscreen Exit')], max_length=20)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('description', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examattempt')),
            ],
        ),
    ]
