# Generated by Django 4.2.30 on 2026-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationlog',
            name='violation_type',
            field=models.CharField(choices=[('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('LOOKING_AWAY', 'Looking Away'), ('PHONE_DETECTED', 'Phone Detected'), ('TAB_SWITCH', 'Tab Switch'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('EYE_LOOKAWAY', 'Eye Gaze Away'), ('HEAD_TURN', 'Head Turn'), ('HEADPHONES', 'Headphones Detected'), ('MULTIPLE_SCREENS', 'Multiple Screens Detected'), ('CLIPBOARD_USE', 'Clipboard Activity Blocked'), ('RIGHT_CLICK', 'Right Click Blocked'), ('HOTKEY_PRESS', 'Restricted Hotkey Pressed'), ('WEBCAM_DISCONNECT', 'Webcam Disconnected'), ('NETWORK_DISCONNECT', 'Internet Disconnected')], max_length=30),
        ),
    ]
