# Generated by Django 4.2.30 on 2026-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allowed_warnings',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_mark_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_calibrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
